server:
  port: 8080

spring:
#  security:
#    user:
#      name: admin
#      password: filmasters
#      roles: ADMIN
  datasource:
    url: jdbc:h2:mem:filmasters
    username: filmasters
    password: filmasters
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false # Não abre conexão com o banco desde o controller, melhorando o desempenho
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    enabled: true