---
name: filmasters-ci/cd
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      fail-fast: true
      matrix:
        java: [21]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin

#      - name: Run docker compose
#        uses: hoverkraft-tech/compose-action@v2.0.1
#        with:
#          compose-file: "docker-compose.yaml"

      - name: Build with gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

  deploy:
    needs: check-application
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fake Deploy Step
        run: |
          echo "🔧 Simulando deploy..."
          sleep 2
          echo "✅ Deploy simulado com sucesso!"
